app = "appname"
primary_region = "ams"

[build]
  [build.args]
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

  AWS_ACCESS_KEY_ID = '%AWS_ACCESS_KEY_ID%'
  AWS_DEFAULT_REGION = '%AWS_DEFAULT_REGION%'
  AWS_BUCKET = '%bucket%'
  AWS_USE_PATH_STYLE_ENDPOINT = 'false'
